### ISSUE TITLE
File import doesn't do anything

### ISSUE THREAD

**Issue by woeterman94** [JohnMcLear/ep_file_menu_toolbar#9]
It opens the file explorer but doesn't do anything? Is it supposed to import images? Or other documents?

**Comment by JohnMcLear** [comment]
Fixed.  Good spot :+1:

**Comment by woeterman94** [comment]
Did you publish it? Or should I just clone this repo?

**Comment by woeterman94** [comment]
Do I need an other plugin or setting? Cause it's still the same behavior

**Comment by JohnMcLear** [comment]
Just git pull or grab latest it should be fixed.  Now on file selection it should show the import now dialog button.  Before it silently failed.
